import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:intl/intl.dart';
import 'package:printing/printing.dart';

class ReportService {
  Future<void> generateMonthlyReport(Map<String, dynamic> insights) async {
    final doc = pw.Document();

    doc.addPage(
      pw.Page(
        build: (pw.Context context) {
          return pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              pw.Header(
                level: 0,
                child: pw.Text('KodiPay Monthly Financial Report',
                    style: pw.TextStyle(fontSize: 24, fontWeight: pw.FontWeight.bold)),
              ),
              pw.SizedBox(height: 20),
              pw.Text('Date: ${DateFormat('yyyy-MM-dd').format(DateTime.now())}'),
              pw.SizedBox(height: 40),
              pw.Text('Summary', style: pw.TextStyle(fontSize: 18, fontWeight: pw.FontWeight.bold)),
              pw.Divider(),
              pw.SizedBox(height: 10),
              _buildSummaryRow('Total Properties', insights['totalProperties'].toString()),
              _buildSummaryRow('Total Units', insights['totalUnits'].toString()),
              _buildSummaryRow('Occupied Units', insights['occupiedUnits'].toString()),
              _buildSummaryRow('Occupancy Rate', '${insights['occupancyRate']}%'),
              _buildSummaryRow('Monthly Revenue Potential', 'KES ${insights['monthlyRevenue']}'),
              pw.SizedBox(height: 40),
              pw.Text('Generated by KodiPay', style: const pw.TextStyle(fontSize: 12, color: PdfColors.grey)),
            ],
          );
        },
      ),
    );

    // Share the PDF (opens system dialog to save/share/print)
    await Printing.sharePdf(
      bytes: await doc.save(),
      filename: 'KodiPay_Report_${DateFormat('yyyyMMdd_HHmmss').format(DateTime.now())}.pdf',
    );
  }

  pw.Widget _buildSummaryRow(String label, String value) {
    return pw.Padding(
      padding: const pw.EdgeInsets.symmetric(vertical: 4),
      child: pw.Row(
        mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
        children: [
          pw.Text(label),
          pw.Text(value, style: pw.TextStyle(fontWeight: pw.FontWeight.bold)),
        ],
      ),
    );
  }
}
